publishdir = "public"
static = "/static"
builddrafts = false
# Replace this with your website URL
baseurl = "https://ScalableTrustworthyAI.github.io"
canonifyurls = true
title = "Scalable Trustworthy AI"
math = true
copyright = "&copy; Seong Joon Oh, 2022"


[taxonomies]
category = "categories"
tag = "tags"


[params]
  author = "Seong Joon Oh"
  email = "coallaoh@gmail.com"
  address = "Maria-von-Linden-Straße 6, 72076 Tübingen, Germany"

  slogan = "Scalable Trustworthy AI"
  slogan_text = "Creating scalable and trustworthy AI with human guidance"

  [params.logo]
    image = "img/stai_logo.png"
    link = "img/stai_logo.png"

  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  [params.publications]
    count = 10
    detailed_list = true
    title = "Publications"
    subtitle = ""
    str_all = "More Publications"

  [params.openings]
    count = 10
    detailed_list = true
    title = "Openings"
    subtitle = ""
    str_all = "More Openings"

  [params.courses]
    count = 10
    detailed_list = true
    title = "Courses"
    subtitle = ""
    str_all = "More Courses"

  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 2
    title = "Blog"
    subtitle = ""
    str_all = "More Posts"
    str_read_more = "Read more"

  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = false  # Automatically link email and phone?

  [[menu.main]]
      name = "Home"
      url = "/#top"
      weight = 1

  [[menu.main]]
      name = "Overview"
      url = "/#overview"
      weight = 2

  [[menu.main]]
      name = "Members"
      url = "/#members"
      weight = 3

  [[menu.main]]
      name = "Publications"
      url = "/#publications"
      weight = 4

  # [[menu.main]]
  #     name = "Blog"
  #     url = "/#posts"
  #     weight = 5

  [[menu.main]]
      name = "Courses"
      url = "/#courses"
      weight = 5

  [[menu.main]]
      name = "Openings"
      url = "/#openings"
      weight = 6

  [[menu.main]]
      name = "Contact"
      url = "/#contact"
      weight = 7
